# -*- coding: utf-8 -*-
"""finalBookAssist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ne8kSkHU3RP4ivwmYLaO5zYKQe4zHzlm
"""

!pip install sumy
!pip install pyrebase
!pip install easyocr

import os
import easyocr
reader = easyocr.Reader(['en'])
import pyrebase
import nltk
import smtplib
nltk.download('punkt')
import time

#getting image from firebase
config = {
  "apiKey": environ['apiKey'],
  "authDomain": environ['authDomain'],
  "databaseURL": environ['databaseURL'],
  "storageBucket": environ['storageBucket']
}

firebase = pyrebase.initialize_app(config)
storage = firebase.storage()
database = firebase.database()

storage.child('/uploaded.png').download('imageFromFirebase.png')

def sendEmail(subject, message):
  tEmail = database.child('teacher').child("email").get().val()

  server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
  password= "ncodehackspass"
  server.login('textbookassist@gmail.com', password)

  server.sendmail('textbookassist@gmail.com', 'sclarkson678@gmail.com', 'Subject: {}\n\n{}'.format(subject, message))
  server.quit()

  print('Message Sent Successfully')

def convertImgToTxt(imgName):
  arrayOfText = reader.readtext(imgName, detail = 0)
  myString = ''

  for i in arrayOfText:
    myString+= (i + " ")
  
  return myString

def summarize(startText):
  output = !sumy luhn --length=50% --language=english --file=input.txt
  formattedOutput = ''
  for i in output:
    formattedOutput += (i + " ")

  return formattedOutput

finalString = convertImgToTxt('imageFromFirebase.png')

database.child('whatWeRead').set(finalString)

myFile = open('input.txt', 'w')
myFile.write(finalString)
myFile.close()

words = finalString.split()

if (len(words) > 75):
  finalString = summarize('imageFromFirebase.png')

database.child('shortenedText').set(finalString)
sendEmail('Message from one of your students!', 'Your student requested that you take a look at this part in your class textbook:'+ '\n\n' + finalString)

database.child('arduinoVal').set(1)
time.sleep(database.child('arduinoTimeDelay').get().val())
database.child('arduinoVal').set(0)